<a href="https://colab.research.google.com/github/Votutu/FDSfE/blob/main/Videos_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

videos = pd.read_csv("https://github.com/fedhere/FDSfE_FBianco/blob/main/data/USyoutubes.csv?raw=true")

videos.shape

videos.describe()

videos.columns
videos[['views', 'likes', 'dislikes', 'comment_count']]

          views   likes  dislikes  comment_count
0        748374   57527      2966          15954
1       2418783   97185      6146          12703
2       3191434  146033      5339           8181
3        343168   10172       666           2146
4       2095731  132235      1989          17518
...         ...     ...       ...            ...
40944   1685609   38160      1385           2657
40945   1064798   60008       382           3936
40946   1066451   48068      1032           3992
40947   5660813  192957      2846          13088
40948  10306119  357079    212976         144795

[40949 rows x 4 columns]